### ISSUE TITLE
ActiveRecord 5.0 internal metadata table should not be cleaned

### ISSUE THREAD

**Issue by md5** [DatabaseCleaner/database_cleaner-active_record#15]
I'm building an app using Rails 5.0.0.rc1 and I ran into the fact that the `ar_internal_metadata` table is being cleaned with the `:truncation` strategy. This is similar to DatabaseCleaner/database_cleaner#317.

When this happens and `ActiveRecord::Migration.maintain_test_schema!` is being used, tests/specs will fail if there are pending migrations and `database_cleaner` has had a chance to run and clear the metadata table. The error looks like this:

```
$ bundle exec rspec
rails aborted!
ActiveRecord::NoEnvironmentInSchemaError: 

Environment data not found in the schema. To resolve this issue, run: 

    bin/rails db:environment:set RAILS_ENV=test

/Users/mike/dev/my_app/bin/rails:9:in `require'
/Users/mike/dev/my_app/bin/rails:9:in `<top (required)>'
/Users/mike/dev/my_app/bin/spring:13:in `require'
/Users/mike/dev/my_app/bin/spring:13:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:test:load => db:test:purge => db:check_protected_environments
(See full trace by running task with --trace)
Coverage report generated for RSpec to /Users/mike/dev/my_app/coverage. 29 / 547 LOC (5.3%) covered.
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/migration.rb:572:in `check_pending!':  (ActiveRecord::PendingMigrationError)

Migrations are pending. To resolve this issue, run:

    bin/rails db:migrate RAILS_ENV=test

    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/migration.rb:585:in `load_schema_if_pending!'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/migration.rb:591:in `block in maintain_test_schema!'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/migration.rb:822:in `suppress_messages'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/migration.rb:596:in `method_missing'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.rc1/lib/active_record/migration.rb:591:in `maintain_test_schema!'
    from /Users/mike/dev/my_app/spec/rails_helper.rb:32:in `<top (required)>'
    from /Users/mike/dev/my_app/spec/controllers/widgets_controller_spec.rb:2:in `require'
    from /Users/mike/dev/my_app/spec/controllers/widgets_controller_spec.rb:2:in `<top (required)>'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta3/lib/rspec/core/configuration.rb:1333:in `load'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta3/lib/rspec/core/configuration.rb:1333:in `block in load_spec_files'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta3/lib/rspec/core/configuration.rb:1331:in `each'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta3/lib/rspec/core/configuration.rb:1331:in `load_spec_files'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta3/lib/rspec/core/runner.rb:106:in `setup'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta3/lib/rspec/core/runner.rb:92:in `run'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta3/lib/rspec/core/runner.rb:78:in `run'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta3/lib/rspec/core/runner.rb:45:in `invoke'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.0.beta3/exe/rspec:4:in `<top (required)>'
    from /usr/local/var/rbenv/versions/2.3.1/bin/rspec:23:in `load'
    from /usr/local/var/rbenv/versions/2.3.1/bin/rspec:23:in `<main>'
```

As with was the case with DatabaseCleaner/database_cleaner#317, adding the table to the `except` list is a workaround:

``` ruby
DatabaseCleaner.clean_with :truncation, except: %w(public.ar_internal_metadata)
```

**Comment by gbirchmeier** [comment]
@botandrose I was working on a demo app to reproduce this problem consistently, and found out that, since my last comment, `database_cleaner` 1.8 has been released and appears to solve the problem.

All I had to do was change `database_cleaner (1.7.0)` to `(1.8.3)` in my `Gemfile.lock`, and the problem went away.  So maybe this is solved?

**Comment by etagwerker** [comment]
@gbirchmeier Yes, I believe this is fixed now. Thanks for confirming that!

**Comment by chase439** [comment]
I'm still getting this error with database_cleaner version 1.8.5 when I run features specs with capybara only.
